# Generated by Django 4.2.4 on 2023-08-24 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('group_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='usergroup',
            name='permissions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='CustomGroup',
        ),
        migrations.AddField(
            model_name='usergroup',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(through='polls.UserGroup', to='polls.group'),
        ),
    ]
