# Generated by Django 4.2.4 on 2023-09-04 22:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_data_adducts_file_data_bounds_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 10, 34, 28, 217091)),
        ),
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
            ],
            options={
                'db_table': 'PostGroup',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(through='polls.PostGroup', to='polls.post'),
        ),
    ]
