# Generated by Django 4.2.4 on 2023-09-04 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_data_adducts_file_data_bounds_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.group')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
            ],
            options={
                'db_table': 'PostGroup',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='posts',
            field=models.ManyToManyField(through='polls.PostGroup', to='polls.post'),
        ),
    ]
