# Generated by Django 4.2.4 on 2023-09-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_postgroup_group_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
    ]
