# Generated by Django 4.2.4 on 2023-09-07 07:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postanalysis',
            name='associated_post',
        ),
        migrations.AddField(
            model_name='post',
            name='associated_results',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.postanalysis'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 19, 8, 47, 202954)),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 19, 8, 47, 202954)),
        ),
    ]
