# Generated by Django 4.2.4 on 2023-09-08 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cover_photo',
            field=models.ImageField(default='N/A', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 11, 52, 27, 674132)),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 9, 11, 52, 27, 674295)),
        ),
    ]
