# Generated by Django 4.2.4 on 2023-09-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_postanalysis_associated_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
