# Generated by Django 4.2.4 on 2023-09-09 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_customuser_cover_photo_alter_post_post_time_and_more'),
        ('polls', '0008_alter_post_post_time_alter_usergroup_join_date'),
    ]

    operations = [
    ]
