# Generated by Django 4.2.4 on 2023-09-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_merge_20230909_0030'),
        ('polls', '0009_merge_20230909_1442'),
    ]

    operations = [
    ]
