# Generated by Django 4.2.4 on 2023-09-25 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_post_post_time_alter_usergroup_join_date'),
        ('polls', '0011_group_group_banner_post_post_pic_and_more'),
    ]

    operations = [
    ]
