# Generated by Django 4.2.4 on 2023-09-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_remove_tag_posts_group_created'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='Data',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Post',
        ),
        migrations.AlterModelTable(
            name='postanalysis',
            table='PostAnalysis',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
        migrations.AlterModelTable(
            name='tagpost',
            table='TagPost',
        ),
    ]
