# Generated by Django 4.2.4 on 2023-09-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_customuser_notepad_alter_post_post_time_and_more'),
        ('polls', '0013_remove_tag_posts_group_created'),
    ]

    operations = [
    ]
