# Generated by Django 4.2.4 on 2023-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_merge_20230926_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='notepad',
            field=models.TextField(default='Click here to enter notes. Text will be converted to markdown when you click out of the text field...'),
        ),
    ]
