# Generated by Django 4.2.4 on 2023-09-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_merge_20230926_1709'),
        ('polls', '0015_alter_customuser_notepad'),
    ]

    operations = [
    ]
