# Generated by Django 4.2.4 on 2023-09-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_merge_20230926_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(default='Click edit profile to update your description, profile picture and banner for your profile.'),
        ),
    ]
