# Generated by Django 4.2.4 on 2023-09-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_data_table_alter_post_table_and_more'),
        ('polls', '0017_alter_customuser_description'),
    ]

    operations = [
    ]
