# Generated by Django 4.2.4 on 2023-10-02 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_merge_20230930_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
            ],
            options={
                'db_table': 'CollaboratorPost',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='collaborations',
            field=models.ManyToManyField(through='polls.CollaboratorPost', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', through='polls.CollaboratorPost', to=settings.AUTH_USER_MODEL),
        ),
    ]
