# Generated by Django 4.2.4 on 2023-10-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_collaboratorpost_customuser_collaborations_and_more'),
        ('polls', '0019_postanalysis_calibrate_postanalysis_max_adducts_and_more'),
    ]

    operations = [
    ]
