# Generated by Django 4.2.4 on 2023-10-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_merge_20231004_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='postanalysis',
            name='manual_calibration',
            field=models.FloatField(default=0),
        ),
    ]
