# Generated by Django 4.2.4 on 2023-10-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_merge_20231004_0133'),
        ('polls', '0021_postanalysis_manual_calibration'),
    ]

    operations = [
    ]
