# Generated by Django 4.2.4 on 2023-10-08 03:27


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_merge_20231005_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
