# Generated by Django 4.2.4 on 2023-10-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_merge_20231005_1937'),
        ('polls', '0023_alter_customuser_profile_pic'),
    ]

    operations = [
    ]
