# Generated by Django 4.2.4 on 2023-10-10 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_merge_20231009_1403'),
        ('polls', '0024_merge_20231010_0607'),
    ]

    operations = [
    ]
