# Generated by Django 4.2.4 on 2023-10-12 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0024_merge_20231009_1407'),
        ('polls', '0025_merge_20231010_0839'),
    ]

    operations = [
    ]
