# Generated by Django 4.2.4 on 2023-10-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0026_merge_20231012_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='interactions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
    ]
