# Generated by Django 4.2.4 on 2023-10-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0027_alter_customuser_profile_pic'),
        ('polls', '0027_post_interactions_alter_customuser_profile_pic'),
    ]

    operations = [
    ]
