# Generated by Django 4.2.4 on 2023-10-20 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0028_merge_20231016_0116'),
        ('polls', '0028_merge_20231016_1434'),
        ('polls', '0028_merge_20231017_2234'),
        ('polls', '0028_merge_20231020_1016'),
    ]

    operations = [
    ]
