# Generated by Django 4.2.4 on 2023-10-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0029_merge_20231020_1152'),
        ('polls', '0029_merge_20231020_1746'),
    ]

    operations = [
    ]
